ENH/TST: Expose exceptions as attributes; simplify tests.
NSLS-II/portable-mds pull request #6
Opened 2016-09-06 19:14 UTC by danielballan

Using NSLS-II/metadatastore#250 these tests can now be simplified.

2016-11-03 22:32 UTC, tacaswell commented
The broken test will be fixed by #10

2016-11-04 15:22 UTC, tacaswell requested changes

2016-11-04 15:22 UTC, tacaswell commented on portable_mds/tests/test_mds.py
> +    test_pickle,
This is the offending test, needs to be left commented out (or be paraterized in mds)

2017-02-02 21:27 UTC, danielballan commented
Belatedly addressed Tom's comment. Self-merging because we keep forgetting about this and I keep tripping over it.

2017-02-02 21:28 UTC, merged